platforms:
  architectures:
# x86_64 architecture #
  - arch: x86_64
    operating_systems:
    - name: debian
      versions:
      - target: '7' 
        build : '7'
      - target: '8'
        build : '7'
    - name: rhel
      versions:
      - target: '5'
        build : '5'
      - target: '6'
        build : '6'
      - target: '7'
        build : '7'
    - name: freebsd
      versions:
      - target: '10'
        build : '10'
      - target: '11'
        build : '10'
    - name: macos
      versions:
      - target: '10.10'
        build : '10.10'
      - target: '10.11'
        build : '10.10'
      - target: '10.12'
        build : '10.10'
      - target: '10.13'
        build : '10.10'
    - name: sles
      versions:
      - target: '11'
        build : '11'
      - target: '12'
        build : '12'
    - name: solaris
      versions:
      - target: '10'
        build : '10'
      - target: '11'
        build : '11'
    - name: ubuntu
      versions:
      - target: '14.04'
        build : '14.04'
      - target: '14.04'
        build : '16.04'
    - name: windows
      versions:
      - target: '2012r2'
        build : '2012r2'
      - target: '2012r2'
        build : '2008r2'
      - target: '2012r2'
        build : '2012'
      - target: '2012r2'
        build : '2016'
# i386 architecture #
  - arch: i386
    operating_systems:
    - name: debian
      versions:
      - target: '7' 
        build : '7'
    - name: rhel
      versions:
      - target: '5'
        build : '5'
      - target: '6'
        build : '6'
    - name: ubuntu
      versions:
      - target: '14.04'
        build : '14.04'
    - name: windows
      versions:
      - target: '2012r2'
        build : '2012r2'
# SPARC architecture #
  - arch: sparc
    operating_systems:
    - name: solaris
      versions:
      - target: '10'
        build : '10'
      - target: '11'
        build : '11'
# powerpc architecture #
  - arch: powerpc
    operating_systems:
    - name: aix
      versions:
      - target: '6.1'
        build : '7.1'
# ppc64(be) architecture #
  - arch: ppc64
    operating_systems:
    - name: rhel
      versions:
      - 7
# ppc64le architecture #
  - arch: ppc64le
    operating_systems:
    - name: rhel
      versions:
      - 7
    - name: ubuntu
      versions:
      - '14.04'
# s390x architecture #
  - arch: s390x
    operating_systems:
    - name: rhel
      versions:
      - 6
      - 7
    - name: sles
      versions:
      - '10'
      - '11'