pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}

pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/scotthain/omnibus-harmony.git', branch: 'whatisthis'
                readYaml: '.omnibus/config.yml'
            }
        }
    }
}
